package com.adanana.blog.dao;

import com.adanana.blog.model.BlogArticle;

import java.util.List;
import java.util.Map;

public interface BlogArticleMapper {

    List<BlogArticle> find(Map<String,Object> params);
    BlogArticle findById (String id);
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated
     */
    int insert(BlogArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated
     */
    int insertSelective(BlogArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated
     */
    BlogArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlogArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BlogArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlogArticle record);
}