package com.adanana.model;

import com.adanana.model.BaseModel;

import java.util.Date;

public class BlogArticle extends BaseModel {

    private Integer id;


    private String title;


    private Long createUser;

    private String content;

    public void BlogArticle (){
        super.setCreateTime(new Date());
        super.setUpdateTime(new Date());
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
 
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.create_user
     *
     * @param createUser the value for blog_article.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.content
     *
     * @return the value of blog_article.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.content
     *
     * @param content the value for blog_article.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}